#:kivy 1.11.1
#: import FadeTransition kivy.uix.screenmanager.FadeTransition

RootWidget:
    transition: FadeTransition()
    Testwidget:
    SecSc:


<Testwidget@BoxLayout>:
    name: "tstw"
    label1: label1
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        ActionBar:
            ActionView:
                ActionPrevious:
                    title: 'kivyapp'
                    with_previous: False

                ActionButton:
                    text: 'I am just a Button.'

        Label:
            id: label1
            size_hint_y: 1
            font_size: 35
            text: root.text
        
        Button:
            id: button1
            font_size: 35
            text: "01"
            on_press: root.buttonClicked()

        Button:
            id: button2
            font_size: 35
            text: "02"
            on_press: root.buttonClicked2()
            
        Button:
            id: button3
            font_size: 35
            text: "03"
            on_press: 
                root.text = 'that'
                root.manager.get_screen("inputscr").l0.text = root.label1.text
                app.root.current = "inputscr"
    
<SecSc>:
    name: "inputscr"
    l0: l0
    t0: t0
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        ActionBar:
            size_hint_y: 0.1
            ActionView:
                ActionPrevious:
                    title: 'return'
                    with_previous: True
                    on_release: app.root.current = "tstw"

                ActionButton:
                    text: 'No response. Looks dead.'
        
                
        BoxLayout:
            TextInput:
                id: t0
                multiline: True
                text: "I like you"
            
            Label:
                id: l0
                text: ''

            Button:
                id: b0
                text: "modify!"
                on_release: root.txtmodify()
